"""Alert domain model.


PURE module: stdlib only. No framework imports.


An :class:`AlertCandidate` is what hot rules (Phase 4 stage 4.3) and warm
rules (Phase 4 stage 4.5) emit when a condition fires. The application
layer dedupes, debounces, persists to ``alerts_notifications``, and routes
to a dispatch channel (Phase 7).


Why "candidate" rather than "alert": at the point a rule fires we have a
*proposed* alert. The dispatcher decides whether it actually goes out
(cooldown / quiet hours / farmer prefs / DLQ retry policy). The
persisted row in ``alerts_notifications`` is the materialized alert;
the in-memory :class:`AlertCandidate` is the proposition.


The :class:`Severity` and :class:`AlertType` value sets are copied verbatim
from the schema CHECK constraints (migration 0001, lines around 697-698).
Any change here MUST be mirrored in a new migration + SCHEMA_DECISIONS.md.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import StrEnum


class Severity(StrEnum):
    """Mirrors ``alerts_notifications.severity`` CHECK ('info','warning','critical')."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertType(StrEnum):
    """Mirrors ``alerts_notifications.alert_type`` CHECK in migration 0001.


    Values are NOT exhaustive of every possible domain event - they are
    exactly the categories the dispatcher and dashboard know how to
    surface. New alert types require both a migration (extend the CHECK)
    and a routing entry in the dispatcher (Phase 7).
    """

    DRY_RUN = "dry_run"
    LOW_WATER = "low_water"
    POWER_OFF = "power_off"
    PUMP_FAULT = "pump_fault"
    SENSOR_FAULT = "sensor_fault"
    RAIN_HEAVY = "rain_heavy"
    FROST = "frost"
    PEST_RISK = "pest_risk"
    DISEASE_RISK = "disease_risk"
    LOW_BATTERY = "low_battery"
    DEVICE_OFFLINE = "device_offline"
    TAMPER = "tamper"


class DispatchStatus(StrEnum):
    """Mirrors ``alerts_notifications.dispatch_status`` (v3, migration 0002).


    State machine: pending -> sent (on success) or failed (on transient
    error, retried by the dispatcher) or dlq (after retry budget exhausted).
    Phase 7 implements the transitions; this enum is the contract every
    layer agrees on.
    """

    PENDING = "pending"
    SENT = "sent"
    FAILED = "failed"
    DLQ = "dlq"


@dataclass(frozen=True, slots=True)
class AlertCandidate:
    """A proposed alert, emitted by a rule, awaiting dispatch decisions.


    The required identity fields (``tenant_id``, ``farm_id``, ``farmer_id``)
    drive RLS isolation on persist. ``device_id`` is optional because some
    alerts originate from cross-plot conditions (e.g. heatwave forecast)
    that aren't device-attributable.


    ``alert_message_marathi`` is generated by the rule using its
    parameterised Marathi template (Phase 4 stage 4.4 - the rule JSON
    files). It's already farmer-ready by the time it leaves the rule
    engine; the dispatcher does not re-template.
    """

    alert_type: AlertType
    severity: Severity
    alert_message_marathi: str

    tenant_id: uuid.UUID
    farm_id: uuid.UUID
    farmer_id: uuid.UUID

    triggered_at: datetime  # tz-aware (.cursorrules #2)

    device_id: str | None = None
    alert_value: Decimal | None = None
    alert_threshold: Decimal | None = None


__all__ = ["AlertCandidate", "AlertType", "DispatchStatus", "Severity"]
