"""Generated field spec for the Data Entry page (from the pilot intake sheet).

Do not hand-edit — regenerate from the sheet. One entry per editable, human-
sourced field on the seven pilot identity/hardware/season tables."""

from __future__ import annotations

PILOT_TENANT = "11111111-1111-1111-1111-111111111111"
FARMER_ID = "aaaaaaaa-1111-1111-1111-111111111111"
FARM_ID = "bbbbbbbb-2222-2222-2222-222222222222"
PLOT_ID = "PLOT_PILOT_001"
MAIN_NODE_ID = "AGR-MN-0001"
INSTALL_ID = "dddddddd-4444-4444-4444-000000000001"

# table -> how the Data Entry page loads/saves its single pilot row.
RECORDS = {
    "tenants": {"pk": "id", "key": PILOT_TENANT},
    "farmers": {"pk": "farmer_id", "key": FARMER_ID},
    "farms": {"pk": "farm_id", "key": FARM_ID},
    "plots": {"pk": "plot_id", "key": PLOT_ID},
    "crop_seasons": {
        "pk": "season_id",
        "key": None,
        "lookup": "plot_id = 'PLOT_PILOT_001' AND crop_name_english = 'Ginger' AND season_status = 'active'",
    },
    "device_registry": {"pk": "device_id", "key": MAIN_NODE_ID},
    "technician_installations": {"pk": "installation_id", "key": INSTALL_ID},
}

SOURCES = ["FI", "FO", "TECH", "OPS", "DEALER", "AGRO"]

FIELDS = [
    {
        "source": "OPS",
        "table": "tenants",
        "col": "name",
        "label": "Name",
        "widget": "text",
        "help": "Business name of the org.",
    },
    {
        "source": "OPS",
        "table": "tenants",
        "col": "slug",
        "label": "Slug",
        "widget": "text",
        "help": "URL-safe identifier.",
    },
    {
        "source": "OPS",
        "table": "tenants",
        "col": "tier",
        "label": "Tier",
        "widget": "select",
        "help": "pilot_internal / basic / standard / pro.",
        "options": ["pilot_internal", "basic", "standard", "pro"],
    },
    {
        "source": "OPS",
        "table": "tenants",
        "col": "features",
        "label": "Features",
        "widget": "text",
        "help": "Feature-flag blob.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "full_name",
        "label": "Full Name",
        "widget": "text",
        "help": "English/roman.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "marathi_name",
        "label": "Marathi Name",
        "widget": "text",
        "help": "Devanagari.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "phone_primary",
        "label": "Phone Primary",
        "widget": "text",
        "help": "E.164.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "phone_secondary",
        "label": "Phone Secondary",
        "widget": "text",
        "help": "Optional.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "whatsapp_number",
        "label": "Whatsapp Number",
        "widget": "text",
        "help": "May equal phone_primary.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "language_preference",
        "label": "Language Preference",
        "widget": "select",
        "help": "marathi / hindi / english.",
        "options": ["marathi", "hindi", "english"],
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "village",
        "label": "Village",
        "widget": "text",
        "help": "Address block.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "taluka",
        "label": "Taluka",
        "widget": "text",
        "help": "Address block.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "district",
        "label": "District",
        "widget": "text",
        "help": "Address block.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "state",
        "label": "State",
        "widget": "text",
        "help": "Address block.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "pin_code",
        "label": "Pin Code",
        "widget": "text",
        "help": "Address block.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "aadhar_number",
        "label": "Aadhar Number",
        "widget": "text",
        "help": "Government ID. Never returned by any API.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "farmer_id_govt",
        "label": "Farmer Id Govt",
        "widget": "text",
        "help": "Government ID.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "education_level",
        "label": "Education Level",
        "widget": "select",
        "help": "primary/secondary/graduate/illiterate.",
        "options": ["primary", "secondary", "graduate", "illiterate"],
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "age_years",
        "label": "Age Years",
        "widget": "number",
        "help": "",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "gender",
        "label": "Gender",
        "widget": "select",
        "help": "male/female/other.",
        "options": ["male", "female", "other"],
    },
    {
        "source": "OPS",
        "table": "farmers",
        "col": "account_status",
        "label": "Account Status",
        "widget": "select",
        "help": "active/inactive/suspended.",
        "options": ["active", "inactive", "suspended"],
    },
    {
        "source": "DEALER",
        "table": "farmers",
        "col": "subscription_tier",
        "label": "Subscription Tier",
        "widget": "select",
        "help": "basic/standard/pro/custom.",
        "options": ["basic", "standard", "pro", "custom"],
    },
    {
        "source": "DEALER",
        "table": "farmers",
        "col": "subscription_start",
        "label": "Subscription Start",
        "widget": "date",
        "help": "Billing date.",
    },
    {
        "source": "DEALER",
        "table": "farmers",
        "col": "subscription_end",
        "label": "Subscription End",
        "widget": "date",
        "help": "Billing date.",
    },
    {
        "source": "FI",
        "table": "farmers",
        "col": "referred_by",
        "label": "Referred By",
        "widget": "text",
        "help": "Word-of-mouth referrer name.",
    },
    {
        "source": "OPS",
        "table": "farmers",
        "col": "notes",
        "label": "Notes",
        "widget": "textarea",
        "help": "Free-form.",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "farm_name",
        "label": "Farm Name",
        "widget": "text",
        "help": "Farmer / land record identifier.",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "survey_number",
        "label": "Survey Number",
        "widget": "text",
        "help": "Farmer / land record identifier.",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "total_area_acre",
        "label": "Total Area Acre",
        "widget": "area",
        "help": "",
    },
    {
        "source": "TECH",
        "table": "farms",
        "col": "gps_lat_center",
        "label": "Gps Lat Center",
        "widget": "number",
        "help": "Recorded by technician at install; falls back to farmer's phone GPS.",
    },
    {
        "source": "TECH",
        "table": "farms",
        "col": "gps_lng_center",
        "label": "Gps Lng Center",
        "widget": "number",
        "help": "Recorded by technician at install; falls back to farmer's phone GPS.",
    },
    {
        "source": "TECH",
        "table": "farms",
        "col": "gps_boundary_geojson",
        "label": "Gps Boundary Geojson",
        "widget": "text",
        "help": "Polygon walked by technician's tool.",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "soil_type",
        "label": "Soil Type",
        "widget": "select",
        "help": "black/red/sandy/loamy/mixed - farmer knowledge.",
        "options": ["black", "red", "sandy", "loamy", "mixed"],
    },
    {
        "source": "OPS",
        "table": "farms",
        "col": "soil_texture",
        "label": "Soil Texture",
        "widget": "number",
        "help": "From optional lab test.",
    },
    {
        "source": "OPS",
        "table": "farms",
        "col": "soil_depth_cm",
        "label": "Soil Depth Cm",
        "widget": "number",
        "help": "From optional lab test.",
    },
    {
        "source": "OPS",
        "table": "farms",
        "col": "soil_organic_carbon_pct",
        "label": "Soil Organic Carbon Pct",
        "widget": "number",
        "help": "From optional lab test.",
    },
    {
        "source": "TECH",
        "table": "farms",
        "col": "terrain_type",
        "label": "Terrain Type",
        "widget": "select",
        "help": "Observed on-site.",
        "options": ["flat", "mild_slope", "steep"],
    },
    {
        "source": "TECH",
        "table": "farms",
        "col": "elevation_m",
        "label": "Elevation M",
        "widget": "number",
        "help": "Observed on-site.",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "water_source_primary",
        "label": "Water Source Primary",
        "widget": "select",
        "help": "well / borewell / pond / canal / tanker / rain.",
        "options": ["well", "borewell", "farm_pond", "canal", "tanker", "rain"],
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "water_source_secondary",
        "label": "Water Source Secondary",
        "widget": "select",
        "help": "well / borewell / pond / canal / tanker / rain.",
        "options": ["well", "borewell", "farm_pond", "canal", "tanker", "rain", "dam", "none"],
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "well_depth_ft",
        "label": "Well Depth Ft",
        "widget": "number",
        "help": "Farmer knowledge.",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "borewell_depth_ft",
        "label": "Borewell Depth Ft",
        "widget": "number",
        "help": "Farmer knowledge.",
    },
    {
        "source": "TECH",
        "table": "farms",
        "col": "borewell_yield_lpm",
        "label": "Borewell Yield Lpm",
        "widget": "number",
        "help": "Measured during install (yield test).",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "farm_pond_capacity_liters",
        "label": "Farm Pond Capacity Liters",
        "widget": "number",
        "help": "",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "irrigation_type",
        "label": "Irrigation Type",
        "widget": "select",
        "help": "drip/sprinkler/flood/furrow/mixed.",
        "options": ["drip", "sprinkler", "flood", "furrow", "mixed"],
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "drip_emitter_lph",
        "label": "Drip Emitter Lph",
        "widget": "number",
        "help": "Nominal emitter flow.",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "irrigation_area_acre",
        "label": "Irrigation Area Acre",
        "widget": "area",
        "help": "",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "electricity_source",
        "label": "Electricity Source",
        "widget": "multiselect",
        "help": "grid/solar_pump/generator/mixed.",
        "options": ["grid", "solar_pump", "generator"],
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "solar_pump_hp",
        "label": "Solar Pump Hp",
        "widget": "number",
        "help": "",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "generator_fuel",
        "label": "Generator Fuel",
        "widget": "text",
        "help": "",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "electricity_feeder_name",
        "label": "Electricity Feeder Name",
        "widget": "text",
        "help": "",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "electricity_schedule_known",
        "label": "Electricity Schedule Known",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "electricity_schedule_json",
        "label": "Electricity Schedule Json",
        "widget": "text",
        "help": "Farmer-declared schedule; overridden by learned schedule (see electricity_schedule_log).",
    },
    {
        "source": "TECH",
        "table": "farms",
        "col": "road_access",
        "label": "Road Access",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "TECH",
        "table": "farms",
        "col": "nearest_town_km",
        "label": "Nearest Town Km",
        "widget": "number",
        "help": "",
    },
    {
        "source": "TECH",
        "table": "farms",
        "col": "mobile_network_quality",
        "label": "Mobile Network Quality",
        "widget": "select",
        "help": "Observed at install.",
        "options": ["excellent", "good", "moderate", "poor"],
    },
    {
        "source": "FI",
        "table": "farms",
        "col": "previous_crops_json",
        "label": "Previous Crops Json",
        "widget": "text",
        "help": "History disclosed at signup.",
    },
    {
        "source": "OPS",
        "table": "plots",
        "col": "plot_number",
        "label": "Plot Number",
        "widget": "number",
        "help": "1, 2, 3... per farm.",
    },
    {
        "source": "FI",
        "table": "plots",
        "col": "plot_name",
        "label": "Plot Name",
        "widget": "text",
        "help": "Farmer's own name for the plot.",
    },
    {
        "source": "FI",
        "table": "plots",
        "col": "area_acre",
        "label": "Area Acre",
        "widget": "area",
        "help": "",
    },
    {
        "source": "TECH",
        "table": "plots",
        "col": "gps_lat",
        "label": "Gps Lat",
        "widget": "number",
        "help": "Centre of plot.",
    },
    {
        "source": "TECH",
        "table": "plots",
        "col": "gps_lng",
        "label": "Gps Lng",
        "widget": "number",
        "help": "Centre of plot.",
    },
    {
        "source": "TECH",
        "table": "plots",
        "col": "gps_boundary_geojson",
        "label": "Gps Boundary Geojson",
        "widget": "text",
        "help": "Polygon.",
    },
    {
        "source": "OPS",
        "table": "plots",
        "col": "soil_type_override",
        "label": "Soil Type Override",
        "widget": "select",
        "help": "Optional plot-specific soil type (rare).",
        "options": ["black", "red"],
    },
    {
        "source": "TECH",
        "table": "plots",
        "col": "drip_line_count",
        "label": "Drip Line Count",
        "widget": "number",
        "help": "",
    },
    {
        "source": "OPS",
        "table": "plots",
        "col": "plot_status",
        "label": "Plot Status",
        "widget": "select",
        "help": "active/fallow/harvested.",
        "options": ["active", "fallow", "harvested"],
    },
    {
        "source": "OPS",
        "table": "crop_seasons",
        "col": "season_name",
        "label": "Season Name",
        "widget": "text",
        "help": 'E.g. "Kharif 2026 - Ginger Mahima".',
    },
    {
        "source": "OPS",
        "table": "crop_seasons",
        "col": "season_type",
        "label": "Season Type",
        "widget": "select",
        "help": "kharif/rabi/summer/perennial.",
        "options": ["kharif", "rabi", "summer", "perennial"],
    },
    {
        "source": "OPS",
        "table": "crop_seasons",
        "col": "year",
        "label": "Year",
        "widget": "number",
        "help": "Calendar year of sowing.",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "crop_name_marathi",
        "label": "Crop Name Marathi",
        "widget": "text",
        "help": "Pilot: Ginger.",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "crop_name_english",
        "label": "Crop Name English",
        "widget": "text",
        "help": "Pilot: Ginger.",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "crop_variety",
        "label": "Crop Variety",
        "widget": "text",
        "help": "Pilot: Mahima.",
    },
    {
        "source": "OPS",
        "table": "crop_seasons",
        "col": "crop_category",
        "label": "Crop Category",
        "widget": "select",
        "help": "cereal/pulse/oilseed/vegetable/fruit/cash_crop/fodder.",
        "options": ["cereal", "pulse", "oilseed", "vegetable", "fruit", "cash_crop", "fodder"],
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "sowing_date",
        "label": "Sowing Date",
        "widget": "date",
        "help": "Farmer-declared.",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "transplanting_date",
        "label": "Transplanting Date",
        "widget": "date",
        "help": "Farmer-declared.",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "expected_harvest_date",
        "label": "Expected Harvest Date",
        "widget": "date",
        "help": "Farmer-declared.",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "actual_harvest_date",
        "label": "Actual Harvest Date",
        "widget": "date",
        "help": "Back-filled.",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "seed_rate_kg_per_acre",
        "label": "Seed Rate Kg Per Acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "seed_cost_per_kg",
        "label": "Seed Cost Per Kg",
        "widget": "number",
        "help": "",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "base_fertilizer_at_sowing",
        "label": "Base Fertilizer At Sowing",
        "widget": "textarea",
        "help": "Free-form.",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "target_yield_qtl_per_acre",
        "label": "Target Yield Qtl Per Acre",
        "widget": "number",
        "help": "Target from farmer expectation.",
    },
    {
        "source": "FI",
        "table": "crop_seasons",
        "col": "actual_yield_qtl_per_acre",
        "label": "Actual Yield Qtl Per Acre",
        "widget": "number",
        "help": "Actual from post-harvest weigh-in.",
    },
    {
        "source": "OPS",
        "table": "crop_seasons",
        "col": "season_status",
        "label": "Season Status",
        "widget": "select",
        "help": "active/completed/abandoned.",
        "options": ["active", "completed", "abandoned"],
    },
    {
        "source": "OPS",
        "table": "crop_seasons",
        "col": "notes",
        "label": "Notes",
        "widget": "textarea",
        "help": "",
    },
    {
        "source": "OPS",
        "table": "device_registry",
        "col": "device_type",
        "label": "Device Type",
        "widget": "text",
        "help": "master_node/sub_node/weather_station.",
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "serial_number",
        "label": "Serial Number",
        "widget": "text",
        "help": "Read from hardware label at install.",
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "mac_address",
        "label": "Mac Address",
        "widget": "text",
        "help": "Read from hardware label at install.",
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "qr_code_data",
        "label": "Qr Code Data",
        "widget": "text",
        "help": "Read from hardware label at install.",
    },
    {
        "source": "OPS",
        "table": "device_registry",
        "col": "device_tier",
        "label": "Device Tier",
        "widget": "text",
        "help": "basic/standard/pro.",
    },
    {
        "source": "OPS",
        "table": "device_registry",
        "col": "manufacture_date",
        "label": "Manufacture Date",
        "widget": "number",
        "help": "Traceability.",
    },
    {
        "source": "OPS",
        "table": "device_registry",
        "col": "batch_number",
        "label": "Batch Number",
        "widget": "number",
        "help": "Traceability.",
    },
    {
        "source": "OPS",
        "table": "device_registry",
        "col": "pcb_version",
        "label": "Pcb Version",
        "widget": "number",
        "help": "Traceability.",
    },
    {
        "source": "OPS",
        "table": "device_registry",
        "col": "firmware_version_latest",
        "label": "Firmware Version Latest",
        "widget": "text",
        "help": "Latest available from OTA.",
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "installation_date",
        "label": "Installation Date",
        "widget": "date",
        "help": "",
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "gps_installed_lat",
        "label": "Gps Installed Lat",
        "widget": "number",
        "help": "Where the device physically sits.",
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "gps_installed_lng",
        "label": "Gps Installed Lng",
        "widget": "number",
        "help": "Where the device physically sits.",
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "pole_height_ft",
        "label": "Pole Height Ft",
        "widget": "number",
        "help": "",
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "enclosure_type",
        "label": "Enclosure Type",
        "widget": "number",
        "help": "",
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "sim_number",
        "label": "Sim Number",
        "widget": "text",
        "help": "",
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "sim_provider",
        "label": "Sim Provider",
        "widget": "select",
        "help": "Pilot uses airtel.",
        "options": ["jio", "airtel", "bsnl"],
    },
    {
        "source": "TECH",
        "table": "device_registry",
        "col": "signal_4g_strength",
        "label": "Signal 4G Strength",
        "widget": "text",
        "help": "Observed at install; refreshed from RSSI reports (planned).",
    },
    {
        "source": "OPS",
        "table": "device_registry",
        "col": "warranty_expiry",
        "label": "Warranty Expiry",
        "widget": "date",
        "help": "",
    },
    {
        "source": "OPS",
        "table": "device_registry",
        "col": "replacement_flag",
        "label": "Replacement Flag",
        "widget": "bool",
        "help": "Flagged for RMA.",
    },
    {
        "source": "OPS",
        "table": "device_registry",
        "col": "notes",
        "label": "Notes",
        "widget": "textarea",
        "help": "",
    },
    {
        "source": "OPS",
        "table": "device_registry",
        "col": "calibration_json",
        "label": "Calibration Json",
        "widget": "text",
        "help": "Legacy - replaced by device_calibration (Round 16).",
    },
    {
        "source": "OPS",
        "table": "technician_installations",
        "col": "technician_name",
        "label": "Technician Name",
        "widget": "text",
        "help": "Staff master data.",
    },
    {
        "source": "OPS",
        "table": "technician_installations",
        "col": "technician_phone",
        "label": "Technician Phone",
        "widget": "text",
        "help": "Staff master data.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "visit_type",
        "label": "Visit Type",
        "widget": "select",
        "help": "installation/service/upgrade/inspection/replacement.",
        "options": ["installation", "service", "upgrade", "inspection", "replacement"],
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "visit_date",
        "label": "Visit Date",
        "widget": "number",
        "help": "Timesheet.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "arrival_time",
        "label": "Arrival Time",
        "widget": "number",
        "help": "Timesheet.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "departure_time",
        "label": "Departure Time",
        "widget": "number",
        "help": "Timesheet.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "duration_hours",
        "label": "Duration Hours",
        "widget": "number",
        "help": "Timesheet.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "devices_installed_json",
        "label": "Devices Installed Json",
        "widget": "text",
        "help": "Which devices were mounted.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "nodes_installed_count",
        "label": "Nodes Installed Count",
        "widget": "number",
        "help": "Physical bill of work.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "solar_panels_installed",
        "label": "Solar Panels Installed",
        "widget": "number",
        "help": "Physical bill of work.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "poles_installed",
        "label": "Poles Installed",
        "widget": "number",
        "help": "Physical bill of work.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "cable_meters_laid",
        "label": "Cable Meters Laid",
        "widget": "number",
        "help": "Physical bill of work.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "soil_type_observed",
        "label": "Soil Type Observed",
        "widget": "text",
        "help": "Hand-observation.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "moisture_at_install",
        "label": "Moisture At Install",
        "widget": "number",
        "help": "Hand-observation.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "well_depth_measured_ft",
        "label": "Well Depth Measured Ft",
        "widget": "number",
        "help": "Physical measurement.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "borewell_yield_tested_lpm",
        "label": "Borewell Yield Tested Lpm",
        "widget": "number",
        "help": "Physical measurement.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "farm_pond_level_pct",
        "label": "Farm Pond Level Pct",
        "widget": "number",
        "help": "Physical measurement.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "water_quality_check",
        "label": "Water Quality Check",
        "widget": "text",
        "help": "Free-form.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "electricity_tested",
        "label": "Electricity Tested",
        "widget": "bool",
        "help": "Bring-up test.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "signal_4g_tested",
        "label": "Signal 4G Tested",
        "widget": "bool",
        "help": "Bring-up test.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "signal_4g_result",
        "label": "Signal 4G Result",
        "widget": "text",
        "help": "Bring-up test.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "whatsapp_test_sent",
        "label": "Whatsapp Test Sent",
        "widget": "bool",
        "help": "Checklist.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "sensors_calibrated",
        "label": "Sensors Calibrated",
        "widget": "bool",
        "help": "Checklist.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "farmer_training_done",
        "label": "Farmer Training Done",
        "widget": "bool",
        "help": "Checklist.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "farmer_training_topics",
        "label": "Farmer Training Topics",
        "widget": "text",
        "help": "What was covered.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "installation_photos_urls",
        "label": "Installation Photos Urls",
        "widget": "text",
        "help": "R2/B2 URLs.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "issues_found",
        "label": "Issues Found",
        "widget": "text",
        "help": "Narrative.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "issues_resolved",
        "label": "Issues Resolved",
        "widget": "text",
        "help": "Narrative.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "pending_work",
        "label": "Pending Work",
        "widget": "text",
        "help": "Narrative.",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "farmer_signature_collected",
        "label": "Farmer Signature Collected",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "installation_quality_score",
        "label": "Installation Quality Score",
        "widget": "number",
        "help": "Self-assessed.",
    },
    {
        "source": "OPS",
        "table": "technician_installations",
        "col": "next_service_due",
        "label": "Next Service Due",
        "widget": "date",
        "help": "",
    },
    {
        "source": "TECH",
        "table": "technician_installations",
        "col": "notes",
        "label": "Notes",
        "widget": "textarea",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "deep_ploughing_done",
        "label": "deep ploughing done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "solarization_done",
        "label": "solarization done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "solarization_weeks",
        "label": "solarization weeks",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "planting_layout",
        "label": "planting layout",
        "widget": "select",
        "help": "",
        "options": ["flat_bed", "ridge_furrow", "broad_ridge"],
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "bed_height_cm",
        "label": "bed height cm",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "bed_width_cm",
        "label": "bed width cm",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "furrow_width_cm",
        "label": "furrow width cm",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "plants_per_acre",
        "label": "plants per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "planting_depth_cm",
        "label": "planting depth cm",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "earthing_up_date",
        "label": "earthing up date",
        "widget": "date",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "earthing_up_2_date",
        "label": "earthing up 2 date",
        "widget": "date",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "mulch_stage_1_done",
        "label": "mulch stage 1 done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "mulch_stage_2_done",
        "label": "mulch stage 2 done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "mulch_stage_3_done",
        "label": "mulch stage 3 done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "n_target_kg_per_acre",
        "label": "n target kg per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "p_target_kg_per_acre",
        "label": "p target kg per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "k_target_kg_per_acre",
        "label": "k target kg per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "n_applied_kg_per_acre",
        "label": "n applied kg per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "p_applied_kg_per_acre",
        "label": "p applied kg per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "k_applied_kg_per_acre",
        "label": "k applied kg per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "n_split_1_date",
        "label": "n split 1 date",
        "widget": "date",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "n_split_2_date",
        "label": "n split 2 date",
        "widget": "date",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "k_late_split_1_date",
        "label": "k late split 1 date",
        "widget": "date",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "k_late_split_2_date",
        "label": "k late split 2 date",
        "widget": "date",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "fym_t_per_acre",
        "label": "fym t per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "fym_fully_decomposed",
        "label": "fym fully decomposed",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "trichoderma_kg_per_acre",
        "label": "trichoderma kg per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "neem_cake_basal_kg_per_acre",
        "label": "neem cake basal kg per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "neem_cake_earthing_kg_per_acre",
        "label": "neem cake earthing kg per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "micronutrient_basal_done",
        "label": "micronutrient basal done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "micronutrient_spray_1_done",
        "label": "micronutrient spray 1 done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "micronutrient_spray_2_done",
        "label": "micronutrient spray 2 done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "hot_water_treatment_done",
        "label": "hot water treatment done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "biofumigation_done",
        "label": "biofumigation done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "azospirillum_psb_done",
        "label": "azospirillum psb done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "marigold_planted",
        "label": "marigold planted",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "target_product",
        "label": "target product",
        "widget": "select",
        "help": "",
        "options": ["green_ginger", "dry_ginger", "seed_rhizome"],
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "affected_plants_removed",
        "label": "affected plants removed",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "bed_former_arranged",
        "label": "bed former arranged",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "bud_orientation_instructed",
        "label": "bud orientation instructed",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "calibration_date",
        "label": "calibration date",
        "widget": "date",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "calibration_done",
        "label": "calibration done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "crop_coefficient_kc",
        "label": "crop coefficient kc",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "drainage_levels_present",
        "label": "drainage levels present",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "drainage_outlet_present",
        "label": "drainage outlet present",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "drip_efficiency_measured",
        "label": "drip efficiency measured",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "drip_flow_lph_per_acre",
        "label": "drip flow lph per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "drip_lateral_spacing_ft",
        "label": "drip lateral spacing ft",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "drip_shifts_per_day",
        "label": "drip shifts per day",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "dripper_spacing_cm",
        "label": "dripper spacing cm",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "drippers_per_acre",
        "label": "drippers per acre",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "dry_recovery_pct_actual",
        "label": "dry recovery pct actual",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "drying_method",
        "label": "drying method",
        "widget": "select",
        "help": "",
        "options": ["none", "simple_sun", "malabar_lime_sulphur", "soda_khar", "powder"],
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "drying_space_ready",
        "label": "drying space ready",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "field_history_rot",
        "label": "field history rot",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "field_history_wilt",
        "label": "field history wilt",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "gap_filling_done",
        "label": "gap filling done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "harvest_route",
        "label": "harvest route",
        "widget": "select",
        "help": "",
        "options": [
            "green_early",
            "green_full",
            "dry_ginger_immediate",
            "dry_ginger_stored",
            "seed_rhizome",
        ],
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "intercrop_selected",
        "label": "intercrop selected",
        "widget": "text",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "limiting_nutrient",
        "label": "limiting nutrient",
        "widget": "select",
        "help": "",
        "options": ["N", "P", "K", "S", "Zn", "Fe", "B", "Mg", "none"],
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "main_drain_connected",
        "label": "main drain connected",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "moisture_probe_depth_cm",
        "label": "moisture probe depth cm",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "pan_coefficient_kp",
        "label": "pan coefficient kp",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "perennial_weeds_removed",
        "label": "perennial weeds removed",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "ppe_available",
        "label": "ppe available",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "processing_trained_operator",
        "label": "processing trained operator",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "produce_washed",
        "label": "produce washed",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "rows_per_bed",
        "label": "rows per bed",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "season_water_plan_basis",
        "label": "season water plan basis",
        "widget": "select",
        "help": "",
        "options": ["poor_year", "average_year", "good_year"],
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "seasonal_water_requirement_litres",
        "label": "seasonal water requirement litres",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "seed_at_planting_kg",
        "label": "seed at planting kg",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "seed_buds_per_piece",
        "label": "seed buds per piece",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "seed_piece_weight_g",
        "label": "seed piece weight g",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "seed_storage_loss_pct",
        "label": "seed storage loss pct",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "seed_storage_method",
        "label": "seed storage method",
        "widget": "select",
        "help": "",
        "options": ["pit", "shade_heap", "cold_store", "purchased_fresh"],
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "seed_stored_kg",
        "label": "seed stored kg",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "shade_pct",
        "label": "shade pct",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "so2_treatment_used",
        "label": "so2 treatment used",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "storage_loss_monthly_pct",
        "label": "storage loss monthly pct",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "vwc_field_capacity",
        "label": "vwc field capacity",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "vwc_saturation",
        "label": "vwc saturation",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "vwc_stress_threshold",
        "label": "vwc stress threshold",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "water_available_oct_feb_litres",
        "label": "water available oct feb litres",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "water_stress_after_earthing_done",
        "label": "water stress after earthing done",
        "widget": "bool",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "water_withdrawal_pct",
        "label": "water withdrawal pct",
        "widget": "number",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "water_withdrawal_start_date",
        "label": "water withdrawal start date",
        "widget": "date",
        "help": "",
    },
    {
        "source": "AGRO",
        "table": "crop_seasons",
        "col": "water_withdrawal_started",
        "label": "water withdrawal started",
        "widget": "bool",
        "help": "",
    },
]
