"""0002 v3 additional tables + tenants tier/features + v3 column patches.

Creates the 13 v3 tables (the 14th, ``tenants``, was created in 0001), extends
``tenants`` with tier/features, seeds the pilot tenant, applies the Part 2.4
column additions to existing source tables, and creates the v3 indexes from
Part 2.6.

See ``docs/SCHEMA_DECISIONS.md`` for the reconciliation notes (notably the
``otp_codes`` non-immutable predicate fix and the ``dispatch_status`` addition).

Revision ID: 0002
Revises: 0001
Create Date: Phase 1
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


PILOT_TENANT_ID = "11111111-1111-1111-1111-111111111111"


UPGRADE_SQL = r"""
-- ===========================================================================
-- tenants: tier + features (v3), then seed the pilot tenant
-- ===========================================================================
ALTER TABLE tenants
    ADD COLUMN tier TEXT NOT NULL DEFAULT 'basic'
        CHECK (tier IN ('pilot_internal','basic','standard','pro')),
    ADD COLUMN features JSONB NOT NULL DEFAULT '{}';

INSERT INTO tenants (id, name, slug, tier, features)
VALUES ('11111111-1111-1111-1111-111111111111',
        'AgroGuardian Pilot — Aurangabad',
        'pilot',
        'pilot_internal',
        '{"all_features_unlocked": true}'::jsonb);

-- ===========================================================================
-- V3 TABLE 1: users (cross-tenant staff; Argon2id PHC string in password_hash)
-- ===========================================================================
CREATE TABLE users (
    user_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email         TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    full_name     TEXT,
    role          TEXT NOT NULL CHECK (role IN ('admin','agronomist','service','technician')),
    phone         TEXT,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX users_email_lower ON users (LOWER(email));
COMMENT ON TABLE users IS 'Internal staff accounts (admin/agronomist/service/technician); not tenant-scoped.';

-- ===========================================================================
-- V3 TABLE 2: otp_codes
-- Partial-index predicate uses only verified_at IS NULL (now() is not IMMUTABLE).
-- ===========================================================================
CREATE TABLE otp_codes (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID REFERENCES tenants(id),
    phone_e164  TEXT NOT NULL,
    code_hash   TEXT NOT NULL,
    transport   TEXT NOT NULL CHECK (transport IN ('whatsapp','sms')),
    wa_message_id TEXT,
    attempts    INT NOT NULL DEFAULT 0,
    expires_at  TIMESTAMPTZ NOT NULL,
    verified_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX otp_codes_phone_unverified ON otp_codes (phone_e164, created_at DESC)
    WHERE verified_at IS NULL;
COMMENT ON TABLE otp_codes IS 'Phone OTP store with expiry, transport, single-use marker.';

-- ===========================================================================
-- V3 TABLE 3: refresh_tokens
-- ===========================================================================
CREATE TABLE refresh_tokens (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token_hash         BYTEA NOT NULL,
    user_or_farmer_id  UUID NOT NULL,
    role               TEXT NOT NULL,
    tenant_id          UUID REFERENCES tenants(id),
    expires_at         TIMESTAMPTZ NOT NULL,
    revoked_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX refresh_tokens_hash ON refresh_tokens (token_hash);
CREATE INDEX refresh_tokens_subject ON refresh_tokens (user_or_farmer_id);
COMMENT ON TABLE refresh_tokens IS 'Hashed refresh tokens with single-use rotation + revocation.';

-- ===========================================================================
-- V3 TABLE 4: audit_log (global; trigger-driven in 0007)
-- ===========================================================================
CREATE TABLE audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type TEXT,
    actor_id   TEXT,
    table_name TEXT NOT NULL,
    row_pk     JSONB,
    operation  TEXT NOT NULL CHECK (operation IN ('INSERT','UPDATE','DELETE')),
    old_data   JSONB,
    new_data   JSONB,
    at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_table_time ON audit_log (table_name, at DESC);
COMMENT ON TABLE audit_log IS 'Trigger-driven write log on master tables (see 0007).';

-- ===========================================================================
-- V3 TABLE 5: notification_dispatch_log
-- ===========================================================================
CREATE TABLE notification_dispatch_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID NOT NULL REFERENCES tenants(id),
    alert_id            BIGINT NOT NULL REFERENCES alerts_notifications(alert_id),
    channel             TEXT NOT NULL CHECK (channel IN ('whatsapp','sms','fcm','email')),
    provider_message_id TEXT,
    status              TEXT NOT NULL CHECK (status IN ('queued','sent','delivered','failed')),
    error_code          TEXT,
    error_message       TEXT,
    dispatched_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT notification_dispatch_log_uq UNIQUE (alert_id, channel)
);
CREATE INDEX notification_dispatch_log_tenant_idx ON notification_dispatch_log (tenant_id);
COMMENT ON TABLE notification_dispatch_log IS 'Per-channel delivery receipts for alerts.';

-- ===========================================================================
-- V3 TABLE 6: notification_dlq
-- ===========================================================================
CREATE TABLE notification_dlq (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenants(id),
    alert_id        BIGINT REFERENCES alerts_notifications(alert_id),
    channels        TEXT[],
    last_error      TEXT,
    retry_count     INT NOT NULL DEFAULT 0,
    moved_to_dlq_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX notification_dlq_tenant_idx ON notification_dlq (tenant_id);
COMMENT ON TABLE notification_dlq IS 'Dead-letter queue for failed alert dispatch.';

-- ===========================================================================
-- V3 TABLE 7: ingest_unmatched
-- ===========================================================================
CREATE TABLE ingest_unmatched (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  UUID REFERENCES tenants(id),
    topic      TEXT NOT NULL,
    payload    JSONB NOT NULL,
    reason     TEXT NOT NULL,
    first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen  TIMESTAMPTZ NOT NULL DEFAULT now(),
    count      INT NOT NULL DEFAULT 1
);
CREATE INDEX ingest_unmatched_seen_idx ON ingest_unmatched (last_seen DESC);
COMMENT ON TABLE ingest_unmatched IS 'Quarantine for unknown tenant/farm/device triplets.';

-- ===========================================================================
-- V3 TABLE 8: event_outbox (global transactional outbox)
-- ===========================================================================
CREATE TABLE event_outbox (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    UUID REFERENCES tenants(id),
    event_name   TEXT NOT NULL,
    payload      JSONB NOT NULL,
    published    BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX event_outbox_unpublished ON event_outbox (created_at)
    WHERE published = FALSE;
COMMENT ON TABLE event_outbox IS 'Optional transactional outbox for domain events.';

-- ===========================================================================
-- V3 TABLE 9: feature_flags
-- ===========================================================================
CREATE TABLE feature_flags (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id  UUID NOT NULL REFERENCES tenants(id),
    flag_name  TEXT NOT NULL,
    enabled    BOOLEAN NOT NULL DEFAULT FALSE,
    payload    JSONB NOT NULL DEFAULT '{}',
    CONSTRAINT feature_flags_uq UNIQUE (tenant_id, flag_name)
);
COMMENT ON TABLE feature_flags IS 'Per-tenant feature toggles.';

-- ===========================================================================
-- V3 TABLE 10: system_config (global, hot-reloadable)
-- ===========================================================================
CREATE TABLE system_config (
    key        TEXT PRIMARY KEY,
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE system_config IS 'Hot-reloadable runtime config (key/value JSONB).';

-- ===========================================================================
-- V3 TABLE 11: chat_messages (T3 farmer chat, 90-day rolling)
-- ===========================================================================
CREATE TABLE chat_messages (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    UUID NOT NULL REFERENCES tenants(id),
    farmer_id    UUID NOT NULL REFERENCES farmers(farmer_id),
    role         TEXT NOT NULL CHECK (role IN ('user','assistant','system')),
    content      TEXT NOT NULL,
    tokens_used  INT,
    llm_cost_inr NUMERIC(10,4),
    context      JSONB,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX chat_messages_farmer_time ON chat_messages (farmer_id, created_at DESC);
COMMENT ON TABLE chat_messages IS 'Tier-3 farmer chat history (90-day rolling retention).';

-- ===========================================================================
-- V3 TABLE 12: calibration_history
-- ===========================================================================
CREATE TABLE calibration_history (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID NOT NULL REFERENCES tenants(id),
    device_id     TEXT NOT NULL REFERENCES device_registry(device_id),
    sensor        TEXT NOT NULL,
    slope         NUMERIC,
    intercept     NUMERIC,
    lab_id        TEXT,
    calibrated_at TIMESTAMPTZ,
    recorded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX calibration_history_device_sensor ON calibration_history (device_id, sensor);
COMMENT ON TABLE calibration_history IS 'Lab calibration log per device per sensor (slope/intercept).';

-- ===========================================================================
-- V3 TABLE 13: wa_inbound_log
-- ===========================================================================
CREATE TABLE wa_inbound_log (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID NOT NULL REFERENCES tenants(id),
    farmer_id     UUID REFERENCES farmers(farmer_id),
    wa_message_id TEXT UNIQUE,
    phone_e164    TEXT NOT NULL,
    body          TEXT,
    received_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed     BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX wa_inbound_log_phone_time ON wa_inbound_log (phone_e164, received_at DESC);
COMMENT ON TABLE wa_inbound_log IS 'Inbound WhatsApp messages (24-h window logic, advisory + OTP unified).';

-- ===========================================================================
-- Part 2.4 column additions to source tables
-- ===========================================================================
ALTER TABLE farmers
    ADD COLUMN phone_hash BYTEA,
    ADD COLUMN phone_encrypted BYTEA;
CREATE UNIQUE INDEX farmers_phone_hash ON farmers (phone_hash);

ALTER TABLE crop_seasons
    ADD COLUMN sowing_date_inferred BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE device_registry
    ADD COLUMN broker_secret_hash TEXT,
    ADD COLUMN calibration_json JSONB NOT NULL DEFAULT '{}';

ALTER TABLE ai_suggestions
    ADD COLUMN prompt_template_version TEXT,
    ADD COLUMN llm_cost_inr NUMERIC(10,4),
    ADD COLUMN confidence_score NUMERIC(4,3),
    ADD COLUMN confidence_band TEXT
        CHECK (confidence_band IN ('autosend','autosend_caveat','queue','block')),
    ADD COLUMN review_status TEXT NOT NULL DEFAULT 'none'
        CHECK (review_status IN ('none','pending','approved','rejected','edited')),
    ADD COLUMN reviewed_by UUID REFERENCES users(user_id),
    ADD COLUMN reviewed_at TIMESTAMPTZ,
    ADD COLUMN review_notes TEXT;
CREATE INDEX ai_suggestions_plot_generated ON ai_suggestions (plot_id, generated_at DESC);

ALTER TABLE alerts_notifications
    ADD COLUMN dispatch_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (dispatch_status IN ('pending','sent','failed','dlq'));
CREATE INDEX alerts_notifications_pending ON alerts_notifications (dispatch_status, severity)
    WHERE dispatch_status = 'pending';
"""


DOWNGRADE_SQL = r"""
DROP INDEX IF EXISTS alerts_notifications_pending;
ALTER TABLE alerts_notifications DROP COLUMN IF EXISTS dispatch_status;

DROP INDEX IF EXISTS ai_suggestions_plot_generated;
ALTER TABLE ai_suggestions
    DROP COLUMN IF EXISTS prompt_template_version,
    DROP COLUMN IF EXISTS llm_cost_inr,
    DROP COLUMN IF EXISTS confidence_score,
    DROP COLUMN IF EXISTS confidence_band,
    DROP COLUMN IF EXISTS review_status,
    DROP COLUMN IF EXISTS reviewed_by,
    DROP COLUMN IF EXISTS reviewed_at,
    DROP COLUMN IF EXISTS review_notes;

ALTER TABLE device_registry
    DROP COLUMN IF EXISTS broker_secret_hash,
    DROP COLUMN IF EXISTS calibration_json;

ALTER TABLE crop_seasons DROP COLUMN IF EXISTS sowing_date_inferred;

DROP INDEX IF EXISTS farmers_phone_hash;
ALTER TABLE farmers
    DROP COLUMN IF EXISTS phone_hash,
    DROP COLUMN IF EXISTS phone_encrypted;

DROP TABLE IF EXISTS wa_inbound_log CASCADE;
DROP TABLE IF EXISTS calibration_history CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS system_config CASCADE;
DROP TABLE IF EXISTS feature_flags CASCADE;
DROP TABLE IF EXISTS event_outbox CASCADE;
DROP TABLE IF EXISTS ingest_unmatched CASCADE;
DROP TABLE IF EXISTS notification_dlq CASCADE;
DROP TABLE IF EXISTS notification_dispatch_log CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS otp_codes CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DELETE FROM tenants WHERE id = '11111111-1111-1111-1111-111111111111';
ALTER TABLE tenants
    DROP COLUMN IF EXISTS tier,
    DROP COLUMN IF EXISTS features;
"""


def upgrade() -> None:
    op.execute(UPGRADE_SQL)


def downgrade() -> None:
    op.execute(DOWNGRADE_SQL)
