"""0005 convert time-series tables to monthly range partitions.

``node_sensor_readings`` and ``weather_station_readings`` are partitioned by
``recorded_at``; ``weather_forecasts`` by ``fetched_at`` (it has no
``recorded_at`` -- see docs/SCHEMA_DECISIONS.md). The three plain tables created
in 0001 are dropped and re-created as partitioned parents with the full column
set, including the Part 2.4 v3 additions for ``node_sensor_readings``. 13
monthly child partitions (current month + 12 forward) are created per table.

This migration assumes the three tables are empty (initial setup). Nothing has
inbound FKs to them, so DROP/CREATE is safe.

Revision ID: 0005
Revises: 0004
Create Date: Phase 1
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Column body shared between the partitioned CREATE and the downgrade plain
# CREATE. Includes 0001 columns + Part 2.4 v3 additions for node readings.
_NODE_COLUMNS = r"""
    reading_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id                      UUID NOT NULL REFERENCES tenants(id),
    node_id                        TEXT NOT NULL REFERENCES device_registry(device_id),
    farm_id                        UUID NOT NULL REFERENCES farms(farm_id),
    plot_id                        TEXT NOT NULL REFERENCES plots(plot_id),
    farmer_id                      UUID NOT NULL REFERENCES farmers(farmer_id),
    recorded_at                    TIMESTAMPTZ NOT NULL,
    received_at_master             TIMESTAMPTZ NOT NULL,
    transmission_type              TEXT NOT NULL CHECK (transmission_type IN ('esp_now','lora','rs485','wifi')),
    signal_rssi_dbm                INT,
    battery_voltage_v              DOUBLE PRECISION,
    battery_percent                DOUBLE PRECISION,
    solar_charging                 BOOLEAN,
    soil_moisture_1_pct            DOUBLE PRECISION,
    soil_moisture_2_pct            DOUBLE PRECISION,
    soil_moisture_avg_pct          DOUBLE PRECISION,
    soil_temp_c                    DOUBLE PRECISION,
    soil_temp_rootzone_c           REAL,
    soil_ph                        DOUBLE PRECISION,
    soil_ec_ms_cm                  DOUBLE PRECISION,
    soil_n_mg_kg                   DOUBLE PRECISION,
    soil_p_mg_kg                   DOUBLE PRECISION,
    soil_k_mg_kg                   DOUBLE PRECISION,
    soil_n_bucket                  SMALLINT,
    soil_p_bucket                  SMALLINT,
    soil_k_bucket                  SMALLINT,
    npk_sensor_raw_hex             TEXT,
    water_flow_lpm                 DOUBLE PRECISION,
    water_volume_liters_session    DOUBLE PRECISION,
    water_volume_liters_cumulative DOUBLE PRECISION,
    valve_status                   TEXT CHECK (valve_status IN ('open','closed','fault')),
    pump_running                   BOOLEAN,
    pump_current_amps              DOUBLE PRECISION,
    pump_runtime_minutes_today     INT,
    dry_run_detected               BOOLEAN,
    tamper_detected                BOOLEAN,
    enclosure_temp_c               DOUBLE PRECISION,
    fault_flags                    TEXT,
    sensor_health_json             JSONB,
    firmware_version               TEXT,
    uptime_seconds                 INT,
    cadence_mode                   TEXT CHECK (cadence_mode IN ('normal','rapid','low_power','storm','maintenance')),
    backlog_pending                BOOLEAN,
    validation_warn                BOOLEAN,
    low_battery_flag               BOOLEAN
"""

_WEATHER_COLUMNS = r"""
    weather_id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id                 UUID NOT NULL REFERENCES tenants(id),
    master_node_id            TEXT NOT NULL REFERENCES device_registry(device_id),
    farm_id                   UUID NOT NULL REFERENCES farms(farm_id),
    recorded_at               TIMESTAMPTZ NOT NULL,
    air_temp_c                DOUBLE PRECISION,
    air_temp_min_c            DOUBLE PRECISION,
    air_temp_max_c            DOUBLE PRECISION,
    humidity_pct              DOUBLE PRECISION,
    dew_point_c               DOUBLE PRECISION,
    atmospheric_pressure_hpa  DOUBLE PRECISION,
    wind_speed_kmh            DOUBLE PRECISION,
    wind_speed_max_gust_kmh   DOUBLE PRECISION,
    wind_direction_degrees    DOUBLE PRECISION,
    wind_direction_cardinal   TEXT,
    rain_mm_current_hour      DOUBLE PRECISION,
    rain_mm_today             DOUBLE PRECISION,
    rain_mm_last_7_days       DOUBLE PRECISION,
    rain_mm_this_season       DOUBLE PRECISION,
    light_intensity_lux       DOUBLE PRECISION,
    uv_index                  DOUBLE PRECISION,
    leaf_wetness_pct          DOUBLE PRECISION,
    fog_detected              BOOLEAN,
    fog_intensity             TEXT CHECK (fog_intensity IN ('none','light','moderate','dense')),
    frost_risk                BOOLEAN,
    heat_stress_index         DOUBLE PRECISION,
    evapotranspiration_mm     DOUBLE PRECISION,
    weather_station_battery_v DOUBLE PRECISION,
    anemometer_fault          BOOLEAN,
    rain_gauge_fault          BOOLEAN
"""

_FORECAST_COLUMNS = r"""
    forecast_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id                 UUID NOT NULL REFERENCES tenants(id),
    farm_id                   UUID NOT NULL REFERENCES farms(farm_id),
    fetched_at                TIMESTAMPTZ NOT NULL,
    forecast_for_date         DATE NOT NULL,
    forecast_hour             INT,
    source_api                TEXT NOT NULL,
    temp_c                    DOUBLE PRECISION,
    temp_min_c                DOUBLE PRECISION,
    temp_max_c                DOUBLE PRECISION,
    humidity_pct              DOUBLE PRECISION,
    rain_probability_pct      DOUBLE PRECISION,
    rain_mm_expected          DOUBLE PRECISION,
    wind_speed_kmh            DOUBLE PRECISION,
    wind_direction            TEXT,
    fog_probability_pct       DOUBLE PRECISION,
    cloud_cover_pct           DOUBLE PRECISION,
    spray_suitability         TEXT CHECK (spray_suitability IN ('good','moderate','poor','not_recommended')),
    irrigation_recommendation TEXT CHECK (irrigation_recommendation IN ('irrigate','skip_rain','reduce','normal')),
    frost_risk                BOOLEAN,
    heat_wave_risk            BOOLEAN
"""


UPGRADE_SQL = rf"""
DROP TABLE IF EXISTS node_sensor_readings CASCADE;
DROP TABLE IF EXISTS weather_station_readings CASCADE;
DROP TABLE IF EXISTS weather_forecasts CASCADE;

-- node_sensor_readings: partitioned by recorded_at -------------------------
CREATE TABLE node_sensor_readings (
{_NODE_COLUMNS},
    PRIMARY KEY (reading_id, recorded_at),
    CONSTRAINT node_sensor_readings_idem UNIQUE (node_id, recorded_at)
) PARTITION BY RANGE (recorded_at);
CREATE INDEX node_sensor_readings_plot_time   ON node_sensor_readings (plot_id, recorded_at DESC);
CREATE INDEX node_sensor_readings_farm_time   ON node_sensor_readings (farm_id, recorded_at DESC);
CREATE INDEX node_sensor_readings_tenant_time ON node_sensor_readings (tenant_id, recorded_at DESC);

-- weather_station_readings: partitioned by recorded_at ---------------------
CREATE TABLE weather_station_readings (
{_WEATHER_COLUMNS},
    PRIMARY KEY (weather_id, recorded_at),
    CONSTRAINT weather_station_readings_idem UNIQUE (master_node_id, recorded_at)
) PARTITION BY RANGE (recorded_at);
CREATE INDEX weather_station_readings_farm_time   ON weather_station_readings (farm_id, recorded_at DESC);
CREATE INDEX weather_station_readings_tenant_time ON weather_station_readings (tenant_id, recorded_at DESC);

-- weather_forecasts: partitioned by fetched_at -----------------------------
CREATE TABLE weather_forecasts (
{_FORECAST_COLUMNS},
    PRIMARY KEY (forecast_id, fetched_at)
) PARTITION BY RANGE (fetched_at);
CREATE INDEX weather_forecasts_lookup ON weather_forecasts (farm_id, forecast_for_date, forecast_hour);
CREATE INDEX weather_forecasts_tenant_time ON weather_forecasts (tenant_id, fetched_at DESC);

-- 13 monthly child partitions (current month + 12 forward) -----------------
DO $$
DECLARE
    i           INT;
    start_date  DATE;
    end_date    DATE;
    base_date   DATE := date_trunc('month', now())::date;
    suffix      TEXT;
BEGIN
    FOR i IN 0..12 LOOP
        start_date := (base_date + (i      || ' month')::interval)::date;
        end_date   := (base_date + ((i + 1) || ' month')::interval)::date;
        suffix     := to_char(start_date, 'YYYYMM');

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS node_sensor_readings_p%s '
            'PARTITION OF node_sensor_readings FOR VALUES FROM (%L) TO (%L);',
            suffix, start_date, end_date);

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS weather_station_readings_p%s '
            'PARTITION OF weather_station_readings FOR VALUES FROM (%L) TO (%L);',
            suffix, start_date, end_date);

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS weather_forecasts_p%s '
            'PARTITION OF weather_forecasts FOR VALUES FROM (%L) TO (%L);',
            suffix, start_date, end_date);
    END LOOP;
END
$$;
"""


# Downgrade re-creates the plain (non-partitioned) tables so 0001/0004 can drop
# them cleanly. Includes the v3 columns (harmless superset).
DOWNGRADE_SQL = rf"""
DROP TABLE IF EXISTS node_sensor_readings CASCADE;
DROP TABLE IF EXISTS weather_station_readings CASCADE;
DROP TABLE IF EXISTS weather_forecasts CASCADE;

CREATE TABLE node_sensor_readings (
{_NODE_COLUMNS},
    PRIMARY KEY (reading_id),
    CONSTRAINT node_sensor_readings_idem UNIQUE (node_id, recorded_at)
);
CREATE TABLE weather_station_readings (
{_WEATHER_COLUMNS},
    PRIMARY KEY (weather_id),
    CONSTRAINT weather_station_readings_idem UNIQUE (master_node_id, recorded_at)
);
CREATE TABLE weather_forecasts (
{_FORECAST_COLUMNS},
    PRIMARY KEY (forecast_id)
);
"""


def upgrade() -> None:
    op.execute(UPGRADE_SQL)


def downgrade() -> None:
    op.execute(DOWNGRADE_SQL)
